### PR TITLE
Crypto Price Version 1.0

### PR DESCRIPTION
**Pull request by V0pe**
### React Crypto Price Application

In this project, I did the following to achieve the goal:
- [ ] Select the [Coin API](https://docs.coinapi.io/) for fetching live data.
- [ ] Build files structure for the React app.
- [ ] Prepare routes and navigation in the app.
- [ ] Display list of cryptos and filter them. `Data come from the Coin API.`
- [ ] Test the application.
- [ ] Style your components to match the design provided.
- [ ] [Deploy the project](https://cryptosprice.netlify.app/)

image

### CODE REVIEW

**Review by codepantha — CHANGES_REQUESTED** [review]
# STATUS: REQUESTED CHANGES ♻️ 

## Hi @V0pe 👋, 

You have done a terrific job so far 👏 👏 
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there 😎 



### Highlights 🎯 
✔️ Descriptive PR
✔️ Good commit history
✔️ Linter checks
✔️ Good UI design

## Suggested changes
_Check the comments under the review._

- [ ] You currently have some tests you have written 👏 I suggest you add some integration tests as stipulated in the project requirements in order to complete this milestone 🙏 
- [ ] You have a nice and detailed video but it does not contain a highlight about a piece of code you find interesting or are proud of writing. Please include it 🙏 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by V0pe** [comment]
@codepantha Thanks for the observation, do you have any other comments that you added because I can't find them .

**Comment by codepantha** [comment]
@V0pe I left some **Suggested changes** for you in my comment. Kindly read through ☝️

**Comment by V0pe** [comment]
@codepantha Thanks for the feedback once again,
- [ ] I have added the integration testing for the Api mocking.
- [ ] I have also added the mock store connection

**Review by BenMukebo — APPROVED** [review]
# Status: Approved  :champagne:  ✔️:confetti_ball: 

## Hi @V0pe, 

### **Congratulations! 🎉 Project Approved ✅**

Good job so far. Well Done.👍🏻 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 


### To Highlight 🎉

- Git flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️
- Good presentation video. ✔️ 
- Your app has been well deployed heavy_check_mark
- Your Design looks awesome, keep rocking :rocket: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers :clinking_glasses:  and Happy coding!!! :dancers:💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
